name: pre-merge
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  premerge:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Lint source code
      run: yarn run lint
    - name: Check if any file is modified
      run: git diff --name-only --exit-code
    - name: Prepare testing
      run: yarn run test:e2e:install
    - name: Run unit tests
      run: yarn run test:unit
    - name: Run e2e tests
      run: yarn run test:e2e
    - name: Run build
      run: yarn run build
    - name: Install pipenv
      run: pip install pipenv
    - name: Install infra
      working-directory: ./infra
      run: pipenv install --dev
    - name: Lint infra source code
      working-directory: ./infra
      run: pipenv run lint
    - name: Format infra source code
      working-directory: ./infra
      run: pipenv run format
    - name: Check if any file is modified
      working-directory: ./infra
      run: git diff --name-only --exit-code
    - name: Run infra test cases
      working-directory: ./infra
      run: pipenv run test
    # - uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
